env:
    - LD_LIBRARY_PATH=/usr/local/lib
language: rust
addons:
  apt:
    packages:
    - libjack-dev
rust:
    - nightly
    - stable
os:
    - linux
notifications:
  email:
    - letang.jeremy@gmail.com
    - mitchell.nordine@gmail.com
script:
    - cargo build --verbose
    - cargo test --verbose
