env:
  - LD_LIBRARY_PATH=/usr/local/lib
notifications:
  email:
    - letang.jeremy@gmail.com
before_install:
  - sudo apt-get update
install:
  - curl http://static.rust-lang.org/rustup.sh | sudo sh -
  - sudo apt-get install libportaudio-dev
script:
  - cargo build
